services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp-zentrale
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
